### ISSUE TITLE
PHP Fatal Error in GET /projects

### ISSUE THREAD

**Issue by jonphipps** [jonphipps/Metadata-Registry#150]
## Error in Registry

**PHP Fatal Error** in **GET /projects**
Uncaught UnexpectedValueException: The stream or file "/home/forge/beta.metadataregistry.org/storage/logs/laravel-2017-03-22.log" could not be opened: failed to open stream: Permission denied in /home/forge/beta.metadataregistry.org/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107
Stack trace:
#0 /home/forge/beta.metadataregistry.org/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(107): Monolog\Handler\StreamHandler->write(Array)
#1 /home/forge/beta.metadataregistry.org/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#2 /home/forge/beta.metadataregistry.org/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#3 /home/forge/beta.metadataregistry.org/vendor/monolog/monolog/src/Monolog/Logger.php(616): Monolog\Logger->addRecord(400, Object(UnexpectedValueException), Array)
#4 /home/forge/beta.metadataregistry.org/ven...

[View on Bugsnag](https://app.bugsnag.com/metadata-management-associates/registry/errors/58d2e6d6465b421700e012ac?event_id=58d2e6d6465b421700e012ad)

## Stacktrace

    /home/forge/beta.metadataregistry.org/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107 - [unknown]

[View full stacktrace](https://app.bugsnag.com/metadata-management-associates/registry/errors/58d2e6d6465b421700e012ac?event_id=58d2e6d6465b421700e012ad)

**Comment by jonphipps** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**PHP Fatal Error** in **GET /**](https://app.bugsnag.com/metadata-management-associates/registry/errors/58d2e6d6465b421700e012ac?event_id=58d2f72b85e9221900b539c9)

**Comment by jonphipps** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**PHP Fatal Error** in **GET /**](https://app.bugsnag.com/metadata-management-associates/registry/errors/58d2e6d6465b421700e012ac?event_id=58d2f72b85e9221900b539c9)

**Comment by jonphipps** [comment]
An error linked to this issue has been reopened in Bugsnag
[**PHP Fatal Error** in **GET /**](https://app.bugsnag.com/metadata-management-associates/registry/errors/58d2e6d6465b421700e012ac?event_id=58d2f72b85e9221900b539c9)

**Comment by jonphipps** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**PHP Fatal Error** in **GET /**](https://app.bugsnag.com/metadata-management-associates/registry/errors/58d2e6d6465b421700e012ac?event_id=58d2f72b85e9221900b539c9)
