### ISSUE TITLE
PHP Fatal Error in GET /

### ISSUE THREAD

**Issue by jonphipps** [jonphipps/Metadata-Registry#152]
## Error in Registry

**PHP Fatal Error** in **GET /**
Uncaught ReflectionException: Class view does not exist in /home/forge/beta.metadataregistry.org/vendor/laravel/framework/src/Illuminate/Container/Container.php:749
Stack trace:
#0 /home/forge/beta.metadataregistry.org/vendor/laravel/framework/src/Illuminate/Container/Container.php(749): ReflectionClass->__construct('view')
#1 /home/forge/beta.metadataregistry.org/vendor/laravel/framework/src/Illuminate/Container/Container.php(644): Illuminate\Container\Container->build('view', Array)
#2 /home/forge/beta.metadataregistry.org/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(709): Illuminate\Container\Container->make('view', Array)
#3 /home/forge/beta.metadataregistry.org/vendor/laravel/framework/src/Illuminate/Container/Container.php(1203): Illuminate\Foundation\Application->make('view')
#4 /home/forge/beta.metadataregistry.org/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(144): Illuminate\Container\Container->offsetGet('Illuminate\\Cont...

[View on Bugsnag](https://app.bugsnag.com/metadata-management-associates/registry/errors/58d2f76c5e3151170001f9e5?event_id=58d2f76c5e3151170001f9e6)

## Stacktrace

    /home/forge/beta.metadataregistry.org/vendor/laravel/framework/src/Illuminate/Container/Container.php:749 - [unknown]

[View full stacktrace](https://app.bugsnag.com/metadata-management-associates/registry/errors/58d2f76c5e3151170001f9e5?event_id=58d2f76c5e3151170001f9e6)

**Comment by jonphipps** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**PHP Fatal Error** in **GET /projects/151**](https://app.bugsnag.com/metadata-management-associates/registry/errors/58d2f76c5e3151170001f9e5?event_id=58d2f7fb84b4a61700cba7b0)

**Comment by jonphipps** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**PHP Fatal Error** in **GET /projects/151**](https://app.bugsnag.com/metadata-management-associates/registry/errors/58d2f76c5e3151170001f9e5?event_id=58d2f7fb84b4a61700cba7b0)

**Comment by jonphipps** [comment]
An error linked to this issue has been reopened in Bugsnag
[**PHP Fatal Error** in **GET /projects/151**](https://app.bugsnag.com/metadata-management-associates/registry/errors/58d2f76c5e3151170001f9e5?event_id=58d2f7fb84b4a61700cba7b0)

**Comment by jonphipps** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**PHP Fatal Error** in **GET /projects/151**](https://app.bugsnag.com/metadata-management-associates/registry/errors/58d2f76c5e3151170001f9e5?event_id=58d2f7fb84b4a61700cba7b0)
